/**
 * Mapping between `public.trades` rows and the app's camelCase shape, following the same
 * pattern as `journalRows.ts`.
 */
import type { Direction } from "../types";
import type { TradeLot } from "./tradeLots";

/** A `trades` row as Supabase returns it. */
export interface TradeRow {
  id: number;
  user_id: string;
  broker: string;

  entry_fill_id: string;
  entry_order_id: string;
  exit_fill_id: string;
  exit_order_id: string;
  lot_seq: number;

  trade_date: string;
  instrument: string;
  type: string;
  exchange: string;
  direction: Direction;

  quantity: number;
  lot: number | null;

  entry_price: number | string;
  exit_price: number | string | null;
  entry_time: string | null;
  exit_time: string | null;

  stop_price: number | string | null;

  /** The basket this leg belongs to, or null when it is a trade on its own. */
  group_id: number | null;
  /** '' until set by hand; the app falls back to the type the instrument implies. */
  trade_type: string;

  /** Option identity, as the broker reports it. */
  underlying: string;
  expiry: string | null;
  strike: number | string | null;
  option_type: string;
  lot_size: number | null;

  /** This lot's share of its orders' charges. Null on rows synced before charges existed. */
  brokerage: number | string | null;
  txn_charges: number | string | null;

  /** Generated by Postgres — never written back. */
  pnl: number | string | null;
  /** pnl less both charges. Null while open or while the charges are unknown. */
  net_pnl: number | string | null;
  initial_risk: number | string | null;
  rr: number | string | null;

  created_at: string;
  updated_at: string;
}

/** One stored lot, as the app uses it. */
export interface DbTrade {
  id: number;
  entryFillId: string;
  exitFillId: string;
  lotSeq: number;

  tradeDate: string;
  instrument: string;
  type: string;
  exchange: string;
  direction: Direction;

  quantity: number;
  lot: number | null;

  entryPrice: number;
  exitPrice: number | null;
  /** hh:mm, trimmed from the Postgres `time` value for display. */
  entryTime: string;
  exitTime: string;

  stopPrice: number | null;

  /** The basket this leg belongs to, or null when it is a trade on its own. */
  groupId: number | null;
  /** '' when never set by hand. Read it through `effectiveType` in `tradeTypes.ts`. */
  tradeType: string;

  /** e.g. NIFTY. '' on rows synced before the column existed. */
  underlying: string;
  /** yyyy-mm-dd, or null for equity and for rows synced before the column existed. */
  expiry: string | null;
  /** 0 for anything that is not an option. */
  strike: number | null;
  /** CE | PE | '' */
  optionType: string;
  lotSize: number | null;

  /** The broker's fee. Null when not known — never read it as zero. */
  brokerage: number | null;
  /** Exchange charges, STT, stamp duty, SEBI fees and GST. */
  txnCharges: number | null;

  /** Gross: price difference times quantity, before any charge. */
  pnl: number | null;
  /** After brokerage and charges. Null while open or while the charges are unknown. */
  netPnl: number | null;
  initialRisk: number | null;
  rr: number | null;

  /** No exit fill yet. */
  open: boolean;
}

/** PostgREST can hand back `numeric` as a string, so every number is coerced on the way in. */
function num(v: number | string | null): number | null {
  if (v === null || v === "") return null;
  const n = Number(v);
  return Number.isFinite(n) ? n : null;
}

export function fromRow(r: TradeRow): DbTrade {
  return {
    id: r.id,
    entryFillId: r.entry_fill_id,
    exitFillId: r.exit_fill_id,
    lotSeq: r.lot_seq,

    tradeDate: r.trade_date,
    instrument: r.instrument,
    type: r.type,
    exchange: r.exchange,
    direction: r.direction,

    quantity: r.quantity,
    lot: r.lot,

    entryPrice: num(r.entry_price) ?? 0,
    exitPrice: num(r.exit_price),
    entryTime: (r.entry_time ?? "").slice(0, 5),
    exitTime: (r.exit_time ?? "").slice(0, 5),

    stopPrice: num(r.stop_price),

    groupId: r.group_id,
    tradeType: r.trade_type ?? "",

    underlying: r.underlying ?? "",
    expiry: r.expiry,
    strike: num(r.strike),
    optionType: r.option_type ?? "",
    lotSize: r.lot_size,

    brokerage: num(r.brokerage),
    txnCharges: num(r.txn_charges),

    pnl: num(r.pnl),
    netPnl: num(r.net_pnl),
    initialRisk: num(r.initial_risk),
    rr: num(r.rr),

    open: r.exit_fill_id === "",
  };
}

/**
 * The columns a sync owns. Deliberately excludes the hand-entered columns, which must survive a
 * re-sync, and the generated columns, which Postgres refuses to accept. The idea, the notes and
 * the strategies all live in `trade_details`, not here.
 *
 * The hand-entered three, none of which may ever appear below:
 *   stop_price  — typed on the table and the detail screen
 *   group_id    — putting this in would silently ungroup every basket on the next sync, and
 *                 nowhere else, which is about the worst failure this file could have
 *   trade_type  — an override; '' means "derive it", so a sync has nothing to say about it
 *
 * The option identity columns below are the opposite: pure broker fact, so a re-sync is free to
 * overwrite them and should.
 *
 * The charges are broker fact too, but are only written when known. A sync whose charges lookup
 * failed leaves whatever an earlier sync stored rather than blanking it — and since an upsert
 * batch nulls any column one of its rows omits, the store upserts priced and unpriced lots
 * separately.
 */
export function toInsert(lot: TradeLot): Record<string, unknown> {
  return {
    entry_fill_id: lot.entryFillId,
    entry_order_id: lot.entryOrderId,
    exit_fill_id: lot.exitFillId,
    exit_order_id: lot.exitOrderId,
    lot_seq: lot.lotSeq,

    trade_date: lot.tradeDate,
    instrument: lot.instrument,
    type: lot.type,
    exchange: lot.exchange,
    direction: lot.direction,

    quantity: lot.quantity,
    lot: lot.lot,

    entry_price: lot.entryPrice,
    exit_price: lot.exitPrice,
    entry_time: lot.entryTime,
    exit_time: lot.exitTime,

    underlying: lot.underlying,
    expiry: lot.expiry,
    strike: lot.strike,
    option_type: lot.optionType,
    lot_size: lot.lotSize,

    ...(lot.brokerage !== null && lot.txnCharges !== null
      ? { brokerage: lot.brokerage, txn_charges: lot.txnCharges }
      : {}),
  };
}
