/**
 * Mapping between `public.trades` rows and the app's camelCase shape, following the same
 * pattern as `journalRows.ts`.
 */
import type { Direction } from "../types";
import type { TradeLot } from "./tradeLots";

/** A `trades` row as Supabase returns it. */
export interface TradeRow {
  id: number;
  user_id: string;
  broker: string;

  entry_fill_id: string;
  entry_order_id: string;
  exit_fill_id: string;
  exit_order_id: string;
  lot_seq: number;

  trade_date: string;
  instrument: string;
  type: string;
  exchange: string;
  direction: Direction;

  quantity: number;
  lot: number | null;

  entry_price: number | string;
  exit_price: number | string | null;
  entry_time: string | null;
  exit_time: string | null;

  stop_price: number | string | null;

  /** Generated by Postgres — never written back. */
  pnl: number | string | null;
  initial_risk: number | string | null;
  rr: number | string | null;

  created_at: string;
  updated_at: string;
}

/** One stored lot, as the app uses it. */
export interface DbTrade {
  id: number;
  entryFillId: string;
  exitFillId: string;
  lotSeq: number;

  tradeDate: string;
  instrument: string;
  type: string;
  exchange: string;
  direction: Direction;

  quantity: number;
  lot: number | null;

  entryPrice: number;
  exitPrice: number | null;
  /** hh:mm, trimmed from the Postgres `time` value for display. */
  entryTime: string;
  exitTime: string;

  stopPrice: number | null;
  pnl: number | null;
  initialRisk: number | null;
  rr: number | null;

  /** No exit fill yet. */
  open: boolean;
}

/** PostgREST can hand back `numeric` as a string, so every number is coerced on the way in. */
function num(v: number | string | null): number | null {
  if (v === null || v === "") return null;
  const n = Number(v);
  return Number.isFinite(n) ? n : null;
}

export function fromRow(r: TradeRow): DbTrade {
  return {
    id: r.id,
    entryFillId: r.entry_fill_id,
    exitFillId: r.exit_fill_id,
    lotSeq: r.lot_seq,

    tradeDate: r.trade_date,
    instrument: r.instrument,
    type: r.type,
    exchange: r.exchange,
    direction: r.direction,

    quantity: r.quantity,
    lot: r.lot,

    entryPrice: num(r.entry_price) ?? 0,
    exitPrice: num(r.exit_price),
    entryTime: (r.entry_time ?? "").slice(0, 5),
    exitTime: (r.exit_time ?? "").slice(0, 5),

    stopPrice: num(r.stop_price),
    pnl: num(r.pnl),
    initialRisk: num(r.initial_risk),
    rr: num(r.rr),

    open: r.exit_fill_id === "",
  };
}

/**
 * The columns a sync owns. Deliberately excludes `stop_price`, the one hand-entered column,
 * which must survive a re-sync, and the generated columns, which Postgres refuses to accept.
 * The idea, the notes and the strategies all live in `trade_details`, not here.
 */
export function toInsert(lot: TradeLot): Record<string, unknown> {
  return {
    entry_fill_id: lot.entryFillId,
    entry_order_id: lot.entryOrderId,
    exit_fill_id: lot.exitFillId,
    exit_order_id: lot.exitOrderId,
    lot_seq: lot.lotSeq,

    trade_date: lot.tradeDate,
    instrument: lot.instrument,
    type: lot.type,
    exchange: lot.exchange,
    direction: lot.direction,

    quantity: lot.quantity,
    lot: lot.lot,

    entry_price: lot.entryPrice,
    exit_price: lot.exitPrice,
    entry_time: lot.entryTime,
    exit_time: lot.exitTime,
  };
}
